### ISSUE TITLE
Hadoop fs path not able to read wasb path

### ISSUE THREAD

**Issue by dheerajkumar-solanki** [Tagar/abalon#1]
```
sc=spark.sparkContext
hadoop=sc._jvm.org.apache.hadoop
conf=hadoop.conf.Configuration()
fs=hadoop.fs.FileSystem.get(conf)
file_path="wasb://container@storageaccount.blob.core.windows.net/file_path"
fs.exists(hadoop.fs.Path(file_path))
```

I am using the above code for checking file existing or not in WASB from HdInsight cluster, it detects successfully when file_path in default container of HdInsight, but can't check in other containers. 

But I can read or write the file in other containers through spark, 
Do I need to set some parameter to work this code?

**Comment by Tagar** [comment]
I never used `wasb:` nor `hdSight`. 
Not sure how this is related to `abalon` codebase.. 
Thanks.

**Comment by dheerajkumar-solanki** [comment]
ok, I think this issue is related to HdInsight and azure storage.
Thanks.
